spring.application.name=VechileAuctionProject


#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/car_auction?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=D3_92737Siddhiraj
spring.datasource.password=bill@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.token.secret=MySuperSecretKeyForJwtToken1234567890
jwt.token.expiration.millis=3600000