spring.application.name=VechileAuctionProject

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/car_auction?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=D3_92737Siddhiraj
spring.datasource.password=bill@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.token.secret=VGhpc0lzQVZlcnlMb25nQW5kU2VjcmV0S2V5Rm9ySldUU2VjdXJpdHk=
jwt.token.expiration.millis=3600000

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

server.tomcat.max-part-count=30
